# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
x.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [6]:
np.__version__
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/data/data/com.termux/files/usr/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/data/data/com.termux/files/usr/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/data/data/com.termux/files/usr/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/data/data/com.termux/files/usr/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


7. Print the dimension of the array in question 3


In [7]:
x.ndim

1

8. Create a boolean array with all the True values

In [8]:
bool_arr = np.ones(10, dtype=bool)
print(bool_arr)

[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [9]:
two_d = np.array([[1,2,3], [2,3,3]])
two_d

array([[1, 2, 3],
       [2, 3, 3]])

10. Create a three dimensional array



In [10]:
three_d = np.array([[[1,2,3], [6,3,4], [2,3,3]]])
three_d.ndim

3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
v = np.array([1,2,3])
v[-1::-1]

array([3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
null = np.zeros(10) 
null[4] = 5
null

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
matrix = np.ones((3,3))
matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(dtype=np.float64)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],
                [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
                [7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
bool_arr = arr1 > arr2
bool_arr

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
ar = np.arange(10)
ar[1::2]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
ar[1::2] = - 1
ar

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
ar[5:9] = 12
ar

array([ 0, -1,  2, -1,  4, 12, 12, 12, 12, -1])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
zero_one_arr = np.ones((4,4))
zero_one_arr[1:3,1:3] = 0
zero_one_arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
_2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
_2d[0] 

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
# using previous one
_2d[1,1] 

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
_2d[0:2,2] 

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
rand = np.random.randn(10,10)
print('Max Value:', np.amax(rand)) 
print('Min Value:', np.amin(rand) ) 

Max Value: 2.4632233513410804
Min Value: -1.6774805994012243


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
np.where(np.in1d(a,b))[0]

array([1, 3, 5, 7])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
indexArr = np.where(names != 'Will')

for index in indexArr:
    print(data[index])

[[-0.36474893 -0.15137446  0.16711057 -0.46487939]
 [-0.53461038 -0.08303664 -1.02891468 -1.67261754]
 [ 0.406581    1.21766449  1.61357781 -0.73801939]
 [ 1.24905416 -0.28670679  0.48014905  0.38359222]
 [-1.95314279 -0.02176636 -0.22335004  0.42332735]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
newdata = data[np.where((names!='Will') | (names != 'Joe'))]
newdata

array([[-0.36474893, -0.15137446,  0.16711057, -0.46487939],
       [-0.53461038, -0.08303664, -1.02891468, -1.67261754],
       [-1.21139937,  0.58555583, -0.08552349,  0.15110109],
       [ 0.406581  ,  1.21766449,  1.61357781, -0.73801939],
       [ 0.33512891, -0.68046167,  0.22574439,  1.41374297],
       [ 1.24905416, -0.28670679,  0.48014905,  0.38359222],
       [-1.95314279, -0.02176636, -0.22335004,  0.42332735]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
values = np.arange(15).reshape((5,3))
values

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
three_d = np.arange(start=1, stop=17, step=1).reshape((2,2,4))
three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [33]:
# using transpose here also
np.transpose(three_d)

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
size_10 = np.arange(start=0, stop=10)
size_10[size_10 ** (0.5) < 0.5] = 0
size_10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
first = np.random.randint(50, size=12)
second = np.random.randint(50, size=12)

result_arr = np.maximum(first, second)
result_arr

array([46, 48, 25, 32, 36, 44, 43, 45, 40,  9, 45, 28])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
sorted = np.sort(np.unique(names))
sorted

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
A = np.array([1,2,3,4,5]) 
B = np.array([5,6,7,8,9])
intersection = np.delete(A, np.where(A == B))
intersection

array([1, 2, 3, 4, 5])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],
                        [82,22,12],
                        [53,94,66]])
newColumn = np.array([[10,10,10]])
newMatrix = np.delete(sampleArray, 1, 1)
newMatrix = np.insert(newMatrix, 1, newColumn, 1)
newMatrix

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.],
              [4., 5., 6.]])

y = np.array([[6.,23],
              [-1, 7],
              [8, 9]])
dot_product = x @ y
dot_product

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
cumSum = np.cumsum(np.random.rand(5, 4))
cumSum

array([0.27097565, 1.23599974, 1.27182441, 1.72796723, 1.95297366,
       2.11839003, 2.87757759, 3.56459794, 3.9605835 , 4.47875825,
       4.88549577, 5.51949546, 6.23713617, 6.44091532, 6.53940331,
       6.89385833, 7.16559021, 7.71314721, 7.77608196, 7.79006204])