# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
# use numpy function: reshape
import numpy as np    
_1d_arr = np.arange(10)
_2d_arr = _1d_arr.reshape((2,5))

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [7]:
# use vertical stack method: vstack
arr1 = np.array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1]])
result = np.vstack((arr1, arr2))
result

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [9]:
# use horizontal stack: hstack
a1 = np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1]])
a2 = np.array([[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
a3 = np.hstack((a1, a2))
a3

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [16]:
array = np.array([[0,1,2], [3,4,5], [6,7,8]])
array.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [ ]:
# use numpy flatten function here!

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [18]:
# we can use reshape method

## Question:7

### Create 5x5 an array and find the square of an array?

In [32]:
squareArray = np.ndarray((5,5))
squareArray ** 2 

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

## Question:8

### Create 5x6 an array and find the mean?

In [41]:
fiveBySix = np.random.randn(5,6)
fiveBySix.mean()

0.3342577722286694

## Question:9

### Find the standard deviation of the previous array in Q8?

In [44]:
fiveBySix.std()

0.9649188082070652

## Question:10

### Find the median of the previous array in Q8?

In [46]:
np.median(fiveBySix)

0.46195805422217195

## Question:11

### Find the transpose of the previous array in Q8?

In [47]:
np.transpose(fiveBySix)

array([[-0.52387797,  0.78371834,  0.18429279,  0.45060649,  1.13185076],
       [-1.27439153, -0.138404  ,  0.24831162, -0.31973068,  0.47330962],
       [ 0.59052859, -0.6841834 ,  1.08794561, -2.04006526,  0.51872771],
       [-1.16033503,  1.77291029,  2.01685803, -0.60783535,  0.09037808],
       [ 0.6069676 , -0.66200666,  0.89523796,  0.97644629, -0.32424407],
       [ 1.69979414,  0.30948822,  0.86533866,  1.08452677,  1.97556955]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [51]:
fourByFour = np.random.randn(4,4)
np.sum(np.diagonal(fourByFour))

4.869028168852547

## Question:13

### Find the determinant of the previous array in Q12?

In [52]:
np.linalg.det(fourByFour)

-3.161950104775834

## Question:14

### Find the 5th and 95th percentile of an array?

In [55]:
array_1d = np.arange(100)

np.percentile(array_1d, 95)
np.percentile(array_1d, 5)

4.95

## Question:15

### How to find if a given array has any null values?

In [56]:
np.any(array_1d == 0)

True